[build]
  # Directorio que contiene los archivos de producción
  publish = "public"
  
  # Comando de construcción (proyecto estático)
  command = "echo 'Static site - no build needed'"

# Configuración de redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers para archivos estáticos con cache
[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para archivos de datos (JSON, CSV)
[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Configuración de manejo de errores
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Variables de entorno para producción (ejemplo)
[context.production.environment]
  NODE_ENV = "production"
  APP_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
  APP_ENV = "preview"